/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/REPLICATE_glue_button_tact.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="REPLICATE_glue_tact_buttonwrl"
          scale={1000}
          userData={{ name: "REPLICATE_glue_tact_button.wrl" }}
          position={[0, -1.75, 0]}
        >
          <group name="Compound" scale={0.0025} userData={{ name: "Compound" }}>
            <group
              name="Compound001"
              position={[0.915, 0.315, -1.713]}
              rotation={[-Math.PI, 0, -Math.PI]}
              userData={{ name: "Compound.001" }}
            >
              <mesh
                name="Compound002"
                castShadow
                receiveShadow
                geometry={nodes.Compound002.geometry}
                material={nodes.Compound002.material}
                userData={{ name: "Compound.002" }}
              />
            </group>
            <group
              name="Compound003"
              position={[2.815, 0.315, 1.476]}
              userData={{ name: "Compound.003" }}
            >
              <mesh
                name="Compound004"
                castShadow
                receiveShadow
                geometry={nodes.Compound004.geometry}
                material={nodes.Compound004.material}
                userData={{ name: "Compound.004" }}
              />
            </group>
            <group
              name="Compound005"
              position={[-2.146, 0.315, 0.059]}
              rotation={[0, Math.PI / 2, 0]}
              userData={{ name: "Compound.005" }}
            >
              <mesh
                name="Compound006"
                castShadow
                receiveShadow
                geometry={nodes.Compound006.geometry}
                material={nodes.Compound006.material}
                userData={{ name: "Compound.006" }}
              />
            </group>
            <group
              name="Compound007"
              position={[0.482, 0.315, 0.153]}
              rotation={[0, -Math.PI / 2, 0]}
              userData={{ name: "Compound.007" }}
            >
              <mesh
                name="Compound008"
                castShadow
                receiveShadow
                geometry={nodes.Compound008.geometry}
                material={nodes.Compound008.material}
                userData={{ name: "Compound.008" }}
              />
            </group>
            <mesh
              name="Compound009"
              castShadow
              receiveShadow
              geometry={nodes.Compound009.geometry}
              material={materials["mat_0.001"]}
              userData={{ name: "Compound.009" }}
            />
            <mesh
              name="Face"
              castShadow
              receiveShadow
              geometry={nodes.Face.geometry}
              material={materials["mat_1.001"]}
              userData={{ name: "Face" }}
            />
            <mesh
              name="Face001"
              castShadow
              receiveShadow
              geometry={nodes.Face001.geometry}
              material={materials["mat_2.001"]}
              userData={{ name: "Face.001" }}
            />
            <mesh
              name="Face002"
              castShadow
              receiveShadow
              geometry={nodes.Face002.geometry}
              material={materials["mat_3.001"]}
              userData={{ name: "Face.002" }}
            />
            <mesh
              name="Face003"
              castShadow
              receiveShadow
              geometry={nodes.Face003.geometry}
              material={materials["mat_3.001"]}
              userData={{ name: "Face.003" }}
            />
            <mesh
              name="Face004"
              castShadow
              receiveShadow
              geometry={nodes.Face004.geometry}
              material={materials["mat_4.001"]}
              userData={{ name: "Face.004" }}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/REPLICATE_glue_button_tact.glb");
