/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/REPLICATE_brain.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="untitledv2wrl" userData={{ name: "untitledv2.wrl" }}>
          <group name="Compound" scale={2.54} userData={{ name: "Compound" }}>
            <group
              name="Compound001"
              position={[8.23, 0.157, 0.138]}
              userData={{ name: "Compound.001" }}
            >
              <group name="Compound002" userData={{ name: "Compound.002" }}>
                <group name="Compound003" userData={{ name: "Compound.003" }}>
                  <group
                    name="Compound004"
                    position={[0, 0.039, 0]}
                    userData={{ name: "Compound.004" }}
                  >
                    <mesh
                      name="Compound005"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound005.geometry}
                      material={materials["mat_0.003"]}
                      userData={{ name: "Compound.005" }}
                    />
                  </group>
                  <group name="Compound006" userData={{ name: "Compound.006" }}>
                    <mesh
                      name="Compound007"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound007.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.007" }}
                    />
                    <mesh
                      name="Compound008"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound008.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.008" }}
                    />
                    <mesh
                      name="Compound009"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound009.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.009" }}
                    />
                    <mesh
                      name="Compound010"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound010.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.010" }}
                    />
                  </group>
                </group>
              </group>
            </group>
            <group
              name="Compound011"
              position={[-1.278, 0.157, -0.217]}
              userData={{ name: "Compound.011" }}
            >
              <group name="Compound012" userData={{ name: "Compound.012" }}>
                <group name="Compound013" userData={{ name: "Compound.013" }}>
                  <group name="Compound014" userData={{ name: "Compound.014" }}>
                    <mesh
                      name="Compound015"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound015.geometry}
                      material={materials["mat_0.003"]}
                      userData={{ name: "Compound.015" }}
                    />
                  </group>
                  <group
                    name="Compound016"
                    position={[-0.709, 0, 0.709]}
                    userData={{ name: "Compound.016" }}
                  >
                    <mesh
                      name="Compound017"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound017.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.017" }}
                    />
                  </group>
                  <group name="Compound018" userData={{ name: "Compound.018" }}>
                    <mesh
                      name="Compound019"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound019.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.019" }}
                    />
                    <mesh
                      name="Compound020"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound020.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.020" }}
                    />
                    <mesh
                      name="Compound021"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound021.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.021" }}
                    />
                    <mesh
                      name="Compound022"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound022.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.022" }}
                    />
                    <mesh
                      name="Compound023"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound023.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.023" }}
                    />
                    <mesh
                      name="Compound024"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound024.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.024" }}
                    />
                    <mesh
                      name="Compound025"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound025.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.025" }}
                    />
                    <mesh
                      name="Compound026"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound026.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.026" }}
                    />
                    <mesh
                      name="Compound027"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound027.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.027" }}
                    />
                    <mesh
                      name="Compound028"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound028.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.028" }}
                    />
                    <mesh
                      name="Compound029"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound029.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.029" }}
                    />
                    <mesh
                      name="Compound030"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound030.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.030" }}
                    />
                    <mesh
                      name="Compound031"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound031.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.031" }}
                    />
                    <mesh
                      name="Compound032"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound032.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.032" }}
                    />
                    <mesh
                      name="Compound033"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound033.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.033" }}
                    />
                    <mesh
                      name="Compound034"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound034.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.034" }}
                    />
                    <mesh
                      name="Compound035"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound035.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.035" }}
                    />
                    <mesh
                      name="Compound036"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound036.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.036" }}
                    />
                    <mesh
                      name="Compound037"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound037.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.037" }}
                    />
                    <mesh
                      name="Compound038"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound038.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.038" }}
                    />
                  </group>
                  <group name="Compound039" userData={{ name: "Compound.039" }}>
                    <mesh
                      name="Compound040"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound040.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.040" }}
                    />
                    <mesh
                      name="Compound041"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound041.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.041" }}
                    />
                    <mesh
                      name="Compound042"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound042.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.042" }}
                    />
                    <mesh
                      name="Compound043"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound043.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.043" }}
                    />
                    <mesh
                      name="Compound044"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound044.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.044" }}
                    />
                    <mesh
                      name="Compound045"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound045.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.045" }}
                    />
                    <mesh
                      name="Compound046"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound046.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.046" }}
                    />
                    <mesh
                      name="Compound047"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound047.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.047" }}
                    />
                    <mesh
                      name="Compound048"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound048.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.048" }}
                    />
                    <mesh
                      name="Compound049"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound049.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.049" }}
                    />
                    <mesh
                      name="Compound050"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound050.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.050" }}
                    />
                    <mesh
                      name="Compound051"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound051.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.051" }}
                    />
                    <mesh
                      name="Compound052"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound052.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.052" }}
                    />
                    <mesh
                      name="Compound053"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound053.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.053" }}
                    />
                    <mesh
                      name="Compound054"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound054.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.054" }}
                    />
                    <mesh
                      name="Compound055"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound055.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.055" }}
                    />
                    <mesh
                      name="Compound056"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound056.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.056" }}
                    />
                    <mesh
                      name="Compound057"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound057.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.057" }}
                    />
                    <mesh
                      name="Compound058"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound058.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.058" }}
                    />
                    <mesh
                      name="Compound059"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound059.geometry}
                      material={materials["mat_1.003"]}
                      userData={{ name: "Compound.059" }}
                    />
                  </group>
                </group>
              </group>
            </group>
            <mesh
              name="Compound060"
              castShadow
              receiveShadow
              geometry={nodes.Compound060.geometry}
              material={materials["mat_2.003"]}
              userData={{ name: "Compound.060" }}
            />
            <mesh
              name="Face"
              castShadow
              receiveShadow
              geometry={nodes.Face.geometry}
              material={materials["mat_3.003"]}
              userData={{ name: "Face" }}
            />
            <mesh
              name="Face001"
              castShadow
              receiveShadow
              geometry={nodes.Face001.geometry}
              material={materials["mat_4.003"]}
              userData={{ name: "Face.001" }}
            />
            <mesh
              name="Face002"
              castShadow
              receiveShadow
              geometry={nodes.Face002.geometry}
              material={materials["mat_5.003"]}
              userData={{ name: "Face.002" }}
            />
            <mesh
              name="Face003"
              castShadow
              receiveShadow
              geometry={nodes.Face003.geometry}
              material={materials["mat_3.003"]}
              userData={{ name: "Face.003" }}
            />
            <mesh
              name="Face004"
              castShadow
              receiveShadow
              geometry={nodes.Face004.geometry}
              material={materials["mat_4.003"]}
              userData={{ name: "Face.004" }}
            />
            <mesh
              name="Face005"
              castShadow
              receiveShadow
              geometry={nodes.Face005.geometry}
              material={materials["mat_5.003"]}
              userData={{ name: "Face.005" }}
            />
            <mesh
              name="Face006"
              castShadow
              receiveShadow
              geometry={nodes.Face006.geometry}
              material={materials["mat_6.003"]}
              userData={{ name: "Face.006" }}
            />
          </group>
        </group>
        <mesh
          name="K3D-ST50S017VCA-V1_JAE_Proprietary"
          castShadow
          receiveShadow
          geometry={nodes["K3D-ST50S017VCA-V1_JAE_Proprietary"].geometry}
          material={materials["Material.001"]}
          position={[-25.225, -0.544, -0.096]}
          rotation={[1.58, -0.025, -1.574]}
          scale={1000}
          userData={{ name: "K3D-ST50S017VCA-V1_JAE_Proprietary" }}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/REPLICATE_brain.glb");
