/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/REPLICATE_neopixel_strip_v2.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="REPLICATE_neopixel_stripwrl"
          userData={{ name: "REPLICATE_neopixel_strip.wrl" }}
        >
          <group name="Compound" scale={2.54} userData={{ name: "Compound" }}>
            <group
              name="Compound001"
              position={[-3.553, 0.315, -0.492]}
              userData={{ name: "Compound.001" }}
            >
              <mesh
                name="Compound002"
                castShadow
                receiveShadow
                geometry={nodes.Compound002.geometry}
                material={nodes.Compound002.material}
                userData={{ name: "Compound.002" }}
              />
            </group>
            <group
              name="Compound003"
              position={[-11.033, 0.315, -0.61]}
              userData={{ name: "Compound.003" }}
            >
              <mesh
                name="Compound004"
                castShadow
                receiveShadow
                geometry={nodes.Compound004.geometry}
                material={nodes.Compound004.material}
                userData={{ name: "Compound.004" }}
              />
            </group>
            <group
              name="Compound005"
              position={[15.423, 0.315, -0.256]}
              rotation={[0, -Math.PI / 2, 0]}
              userData={{ name: "Compound.005" }}
            >
              <mesh
                name="Compound006"
                castShadow
                receiveShadow
                geometry={nodes.Compound006.geometry}
                material={nodes.Compound006.material}
                userData={{ name: "Compound.006" }}
              />
            </group>
            <group
              name="Compound007"
              position={[7.864, 0.315, -0.492]}
              userData={{ name: "Compound.007" }}
            >
              <mesh
                name="Compound008"
                castShadow
                receiveShadow
                geometry={nodes.Compound008.geometry}
                material={nodes.Compound008.material}
                userData={{ name: "Compound.008" }}
              />
            </group>
            <group
              name="Compound009"
              position={[0.384, 0.315, -0.492]}
              userData={{ name: "Compound.009" }}
            >
              <mesh
                name="Compound010"
                castShadow
                receiveShadow
                geometry={nodes.Compound010.geometry}
                material={nodes.Compound010.material}
                userData={{ name: "Compound.010" }}
              />
            </group>
            <group
              name="Compound011"
              position={[16.122, 0.315, -2.377]}
              rotation={[-Math.PI, 0, -Math.PI]}
              userData={{ name: "Compound.011" }}
            >
              <mesh
                name="Compound012"
                castShadow
                receiveShadow
                geometry={nodes.Compound012.geometry}
                material={nodes.Compound012.material}
                userData={{ name: "Compound.012" }}
              />
            </group>
            <group
              name="Compound013"
              position={[4.104, 0.315, -0.492]}
              userData={{ name: "Compound.013" }}
            >
              <mesh
                name="Compound014"
                castShadow
                receiveShadow
                geometry={nodes.Compound014.geometry}
                material={nodes.Compound014.material}
                userData={{ name: "Compound.014" }}
              />
            </group>
            <group
              name="Compound015"
              position={[17.343, 0.315, 1.718]}
              userData={{ name: "Compound.015" }}
            >
              <mesh
                name="Compound016"
                castShadow
                receiveShadow
                geometry={nodes.Compound016.geometry}
                material={nodes.Compound016.material}
                userData={{ name: "Compound.016" }}
              />
            </group>
            <group
              name="Compound017"
              position={[11.585, 0.315, -0.492]}
              userData={{ name: "Compound.017" }}
            >
              <mesh
                name="Compound018"
                castShadow
                receiveShadow
                geometry={nodes.Compound018.geometry}
                material={nodes.Compound018.material}
                userData={{ name: "Compound.018" }}
              />
            </group>
            <group
              name="Compound019"
              position={[-14.577, 0.315, -0.61]}
              userData={{ name: "Compound.019" }}
            >
              <mesh
                name="Compound020"
                castShadow
                receiveShadow
                geometry={nodes.Compound020.geometry}
                material={nodes.Compound020.material}
                userData={{ name: "Compound.020" }}
              />
            </group>
            <group
              name="Compound021"
              position={[-7.313, 0.315, -0.61]}
              userData={{ name: "Compound.021" }}
            >
              <mesh
                name="Compound022"
                castShadow
                receiveShadow
                geometry={nodes.Compound022.geometry}
                material={nodes.Compound022.material}
                userData={{ name: "Compound.022" }}
              />
            </group>
            <mesh
              name="Compound023"
              castShadow
              receiveShadow
              geometry={nodes.Compound023.geometry}
              material={materials.mat_0}
              userData={{ name: "Compound.023" }}
            />
            <mesh
              name="Face"
              castShadow
              receiveShadow
              geometry={nodes.Face.geometry}
              material={materials.mat_1}
              userData={{ name: "Face" }}
            />
            <mesh
              name="Face001"
              castShadow
              receiveShadow
              geometry={nodes.Face001.geometry}
              material={materials.mat_2}
              userData={{ name: "Face.001" }}
            />
            <mesh
              name="Face002"
              castShadow
              receiveShadow
              geometry={nodes.Face002.geometry}
              material={materials.mat_3}
              userData={{ name: "Face.002" }}
            />
            <mesh
              name="Face003"
              castShadow
              receiveShadow
              geometry={nodes.Face003.geometry}
              material={materials.mat_3}
              userData={{ name: "Face.003" }}
            />
            <mesh
              name="Face004"
              castShadow
              receiveShadow
              geometry={nodes.Face004.geometry}
              material={materials.mat_4}
              userData={{ name: "Face.004" }}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/REPLICATE_neopixel_strip_v2.glb");
