/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/REPLICATE_glue_potentiometer_rotary.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="REPLICATE_glue_rotarywrl"
          userData={{ name: "REPLICATE_glue_rotary.wrl" }}
          scale={1000}
          position={[0, -1.75, 0]}
        >
          <group name="Compound" scale={0.0025} userData={{ name: "Compound" }}>
            <group
              name="Compound001"
              position={[4.705, 0.315, 1.919]}
              userData={{ name: "Compound.001" }}
            >
              <mesh
                name="Compound002"
                castShadow
                receiveShadow
                geometry={nodes.Compound002.geometry}
                material={nodes.Compound002.material}
                userData={{ name: "Compound.002" }}
              />
            </group>
            <group
              name="Compound003"
              position={[3.504, 0.315, -2.037]}
              rotation={[-Math.PI, 0, -Math.PI]}
              userData={{ name: "Compound.003" }}
            >
              <mesh
                name="Compound004"
                castShadow
                receiveShadow
                geometry={nodes.Compound004.geometry}
                material={nodes.Compound004.material}
                userData={{ name: "Compound.004" }}
              />
            </group>
            <group
              name="Compound005"
              position={[2.844, 0.315, -0.084]}
              rotation={[0, -Math.PI / 2, 0]}
              userData={{ name: "Compound.005" }}
            >
              <mesh
                name="Compound006"
                castShadow
                receiveShadow
                geometry={nodes.Compound006.geometry}
                material={nodes.Compound006.material}
                userData={{ name: "Compound.006" }}
              />
            </group>
            <group
              name="Compound007"
              position={[-1.378, 0.315, 0.01]}
              rotation={[0, Math.PI / 2, 0]}
              userData={{ name: "Compound.007" }}
            >
              <group name="Compound008" userData={{ name: "Compound.008" }}>
                <group name="Compound009" userData={{ name: "Compound.009" }}>
                  <group name="Compound010" userData={{ name: "Compound.010" }}>
                    <mesh
                      name="Compound003_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound003_1.geometry}
                      material={materials.mat_0}
                    />
                    <mesh
                      name="Compound003_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound003_2.geometry}
                      material={materials.mat_1}
                    />
                  </group>
                  <mesh
                    name="Compound011"
                    castShadow
                    receiveShadow
                    geometry={nodes.Compound011.geometry}
                    material={materials.mat_2}
                    userData={{ name: "Compound.011" }}
                  />
                  <mesh
                    name="Compound012"
                    castShadow
                    receiveShadow
                    geometry={nodes.Compound012.geometry}
                    material={materials.mat_2}
                    userData={{ name: "Compound.012" }}
                  />
                  <mesh
                    name="Compound013"
                    castShadow
                    receiveShadow
                    geometry={nodes.Compound013.geometry}
                    material={materials.mat_2}
                    userData={{ name: "Compound.013" }}
                  />
                  <mesh
                    name="Compound014"
                    castShadow
                    receiveShadow
                    geometry={nodes.Compound014.geometry}
                    material={materials.mat_2}
                    userData={{ name: "Compound.014" }}
                  />
                  <mesh
                    name="Compound015"
                    castShadow
                    receiveShadow
                    geometry={nodes.Compound015.geometry}
                    material={materials.mat_0}
                    userData={{ name: "Compound.015" }}
                  />
                </group>
              </group>
            </group>
            <mesh
              name="Compound016"
              castShadow
              receiveShadow
              geometry={nodes.Compound016.geometry}
              material={materials.mat_3}
              userData={{ name: "Compound.016" }}
            />
            <mesh
              name="Face"
              castShadow
              receiveShadow
              geometry={nodes.Face.geometry}
              material={materials.mat_4}
              userData={{ name: "Face" }}
            />
            <mesh
              name="Face001"
              castShadow
              receiveShadow
              geometry={nodes.Face001.geometry}
              material={materials.mat_5}
              userData={{ name: "Face.001" }}
            />
            <mesh
              name="Face002"
              castShadow
              receiveShadow
              geometry={nodes.Face002.geometry}
              material={materials.mat_6}
              userData={{ name: "Face.002" }}
            />
            <mesh
              name="Face003"
              castShadow
              receiveShadow
              geometry={nodes.Face003.geometry}
              material={materials.mat_4}
              userData={{ name: "Face.003" }}
            />
            <mesh
              name="Face004"
              castShadow
              receiveShadow
              geometry={nodes.Face004.geometry}
              material={materials.mat_6}
              userData={{ name: "Face.004" }}
            />
            <mesh
              name="Face005"
              castShadow
              receiveShadow
              geometry={nodes.Face005.geometry}
              material={materials.mat_7}
              userData={{ name: "Face.005" }}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/REPLICATE_glue_potentiometer_rotary.glb");
