/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function TestModel(props) {
  const { nodes, materials } = useGLTF("/models/test_removed_roughness.glb");
  return (
    <group {...props} dispose={null}>
      <group>
        <group userData={{ name: "test.wrl" }}>
          <group scale={2.54} userData={{ name: "Compound" }}>
            <group
              position={[1.183, 0.315, -4.669]}
              userData={{ name: "Compound.001" }}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Compound002.geometry}
                material={nodes.Compound002.material}
                userData={{ name: "Compound.002" }}
              />
            </group>
            <group
              position={[-3.834, 0.315, 0.118]}
              userData={{ name: "Compound.003" }}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Compound004.geometry}
                material={nodes.Compound004.material}
                userData={{ name: "Compound.004" }}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Compound005.geometry}
              material={materials.mat_0}
              userData={{ name: "Compound.005" }}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Face.geometry}
              material={materials.mat_1}
              userData={{ name: "Face" }}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Face001.geometry}
              material={materials.mat_2}
              userData={{ name: "Face.001" }}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Face002.geometry}
              material={materials.mat_3}
              userData={{ name: "Face.002" }}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Face003.geometry}
              material={materials.mat_1}
              userData={{ name: "Face.003" }}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Face004.geometry}
              material={materials.mat_3}
              userData={{ name: "Face.004" }}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Face005.geometry}
              material={materials.mat_4}
              userData={{ name: "Face.005" }}
            />
          </group>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.Material}
          userData={{ name: "Cube" }}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/test_removed_roughness.glb");
