/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/kittenbot/ec30_2x2_lr_mh_0.1_magnet_sensor.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group name="JD_PWR" position={[-10, 0, 10]}></group>
      <group name="JD_GND1" position={[10, 0, 10]}></group>
      <group name="JD_DATA" position={[-10, 0, -10]}></group>
      <group name="JD_GND2" position={[10, 0, -10.05]}></group>
      <group name="Scene">
        <group
          name="ec30_2x2_lr_mh_01_magnet_sensorwrl"
          userData={{ name: "ec30_2x2_lr_mh_0.1_magnet_sensor.wrl" }}
        >
          <group name="Compound" scale={2.54} userData={{ name: "Compound" }}>
            <group
              name="Compound001"
              position={[0, 1.496, 0]}
              scale={0.394}
              userData={{ name: "Compound.001" }}
            >
              <group name="Compound002" userData={{ name: "Compound.002" }}>
                <group
                  name="Compound003"
                  scale={2.54}
                  userData={{ name: "Compound.003" }}
                >
                  <group
                    name="Compound004"
                    position={[-1.564, 0.315, -3.072]}
                    rotation={[0, -Math.PI / 2, 0]}
                    userData={{ name: "Compound.004" }}
                  >
                    <mesh
                      name="Compound005"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound005.geometry}
                      material={nodes.Compound005.material}
                      userData={{ name: "Compound.005" }}
                    />
                  </group>
                  <group
                    name="Compound006"
                    position={[0.2, 0.315, -3.075]}
                    rotation={[0, -Math.PI / 2, 0]}
                    userData={{ name: "Compound.006" }}
                  >
                    <mesh
                      name="Compound007"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound007.geometry}
                      material={nodes.Compound007.material}
                      userData={{ name: "Compound.007" }}
                    />
                  </group>
                  <group
                    name="Compound008"
                    position={[-1.684, 0.315, 2.01]}
                    rotation={[0, -Math.PI / 2, 0]}
                    userData={{ name: "Compound.008" }}
                  >
                    <mesh
                      name="Compound009"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound009.geometry}
                      material={nodes.Compound009.material}
                      userData={{ name: "Compound.009" }}
                    />
                  </group>
                  <group
                    name="Compound010"
                    position={[1.084, 0.315, -3.476]}
                    rotation={[0, -Math.PI / 2, 0]}
                    userData={{ name: "Compound.010" }}
                  >
                    <mesh
                      name="Compound011"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound011.geometry}
                      material={nodes.Compound011.material}
                      userData={{ name: "Compound.011" }}
                    />
                  </group>
                  <group
                    name="Compound012"
                    position={[2.261, 0.315, 1.803]}
                    userData={{ name: "Compound.012" }}
                  >
                    <mesh
                      name="Compound013"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound013.geometry}
                      material={nodes.Compound013.material}
                      userData={{ name: "Compound.013" }}
                    />
                  </group>
                  <group
                    name="Compound014"
                    position={[-0.676, 0.315, -3.472]}
                    rotation={[0, Math.PI / 2, 0]}
                    userData={{ name: "Compound.014" }}
                  >
                    <mesh
                      name="Compound015"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound015.geometry}
                      material={nodes.Compound015.material}
                      userData={{ name: "Compound.015" }}
                    />
                  </group>
                  <group
                    name="Compound016"
                    position={[2.261, 0.315, 2.583]}
                    userData={{ name: "Compound.016" }}
                  >
                    <mesh
                      name="Compound017"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound017.geometry}
                      material={nodes.Compound017.material}
                      userData={{ name: "Compound.017" }}
                    />
                  </group>
                  <group
                    name="Compound018"
                    position={[2.261, 0.315, 2.193]}
                    rotation={[-Math.PI, 0, -Math.PI]}
                    userData={{ name: "Compound.018" }}
                  >
                    <mesh
                      name="Compound019"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound019.geometry}
                      material={nodes.Compound019.material}
                      userData={{ name: "Compound.019" }}
                    />
                  </group>
                  <group
                    name="Compound020"
                    position={[1.895, 0.315, 0]}
                    rotation={[0, Math.PI / 2, 0]}
                    userData={{ name: "Compound.020" }}
                  >
                    <mesh
                      name="Compound021"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound021.geometry}
                      material={nodes.Compound021.material}
                      userData={{ name: "Compound.021" }}
                    />
                  </group>
                  <group
                    name="Compound022"
                    position={[-2.441, 0.315, 0.008]}
                    rotation={[0, -Math.PI / 2, 0]}
                    userData={{ name: "Compound.022" }}
                  >
                    <mesh
                      name="Compound023"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound023.geometry}
                      material={nodes.Compound023.material}
                      userData={{ name: "Compound.023" }}
                    />
                  </group>
                  <group
                    name="Compound024"
                    position={[0.389, 0.315, 0.974]}
                    rotation={[-Math.PI, 0, -Math.PI]}
                    userData={{ name: "Compound.024" }}
                  >
                    <mesh
                      name="Compound025"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound025.geometry}
                      material={nodes.Compound025.material}
                      userData={{ name: "Compound.025" }}
                    />
                  </group>
                  <group
                    name="Compound026"
                    position={[-0.368, 0.315, 0.974]}
                    userData={{ name: "Compound.026" }}
                  >
                    <mesh
                      name="Compound027"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound027.geometry}
                      material={nodes.Compound027.material}
                      userData={{ name: "Compound.027" }}
                    />
                  </group>
                  <group
                    name="Compound028"
                    position={[0, 0.315, 0]}
                    rotation={[0, Math.PI / 2, 0]}
                    userData={{ name: "Compound.028" }}
                  >
                    <mesh
                      name="Compound029"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound029.geometry}
                      material={nodes.Compound029.material}
                      userData={{ name: "Compound.029" }}
                    />
                  </group>
                  <group
                    name="Compound030"
                    position={[0.002, 0.315, 2.569]}
                    userData={{ name: "Compound.030" }}
                  >
                    <group
                      name="Compound031"
                      userData={{ name: "Compound.031" }}
                    >
                      <group
                        name="Compound032"
                        userData={{ name: "Compound.032" }}
                      >
                        <group
                          name="Compound033"
                          userData={{ name: "Compound.033" }}
                        >
                          <mesh
                            name="Compound051"
                            castShadow
                            receiveShadow
                            geometry={nodes.Compound051.geometry}
                            material={materials["mat_0.002"]}
                          />
                          <mesh
                            name="Compound051_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.Compound051_1.geometry}
                            material={materials["mat_1.002"]}
                          />
                          <mesh
                            name="Compound051_2"
                            castShadow
                            receiveShadow
                            geometry={nodes.Compound051_2.geometry}
                            material={materials["mat_2.002"]}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    name="Compound034"
                    position={[-1.684, 0.315, 3.051]}
                    rotation={[0, Math.PI / 2, 0]}
                    userData={{ name: "Compound.034" }}
                  >
                    <mesh
                      name="Compound035"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound035.geometry}
                      material={nodes.Compound035.material}
                      userData={{ name: "Compound.035" }}
                    />
                  </group>
                  <group
                    name="Compound036"
                    position={[2.441, 0.315, -0.008]}
                    rotation={[0, Math.PI / 2, 0]}
                    userData={{ name: "Compound.036" }}
                  >
                    <mesh
                      name="Compound037"
                      castShadow
                      receiveShadow
                      geometry={nodes.Compound037.geometry}
                      material={nodes.Compound037.material}
                      userData={{ name: "Compound.037" }}
                    />
                  </group>
                  <mesh
                    name="Compound038"
                    castShadow
                    receiveShadow
                    geometry={nodes.Compound038.geometry}
                    material={materials["mat_3.002"]}
                    userData={{ name: "Compound.038" }}
                  />
                  <mesh
                    name="Face"
                    castShadow
                    receiveShadow
                    geometry={nodes.Face.geometry}
                    material={materials["mat_4.002"]}
                    userData={{ name: "Face" }}
                  />
                  <mesh
                    name="Face001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Face001.geometry}
                    material={materials["mat_5.002"]}
                    userData={{ name: "Face.001" }}
                  />
                  <mesh
                    name="Face002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Face002.geometry}
                    material={materials["mat_6.002"]}
                    userData={{ name: "Face.002" }}
                  />
                  <mesh
                    name="Face003"
                    castShadow
                    receiveShadow
                    geometry={nodes.Face003.geometry}
                    material={materials["mat_4.002"]}
                    userData={{ name: "Face.003" }}
                  />
                  <mesh
                    name="Face004"
                    castShadow
                    receiveShadow
                    geometry={nodes.Face004.geometry}
                    material={materials["mat_6.002"]}
                    userData={{ name: "Face.004" }}
                  />
                  <mesh
                    name="Face005"
                    castShadow
                    receiveShadow
                    geometry={nodes.Face005.geometry}
                    material={materials["mat_7.002"]}
                    userData={{ name: "Face.005" }}
                  />
                  <mesh
                    name="Face006"
                    castShadow
                    receiveShadow
                    geometry={nodes.Face006.geometry}
                    material={materials["mat_7.002"]}
                    userData={{ name: "Face.006" }}
                  />
                </group>
              </group>
            </group>
            <mesh
              name="Compound039"
              castShadow
              receiveShadow
              geometry={nodes.Compound039.geometry}
              material={materials["mat_3.002"]}
              userData={{ name: "Compound.039" }}
            />
            <mesh
              name="Face007"
              castShadow
              receiveShadow
              geometry={nodes.Face007.geometry}
              material={materials["mat_4.002"]}
              userData={{ name: "Face.007" }}
            />
            <mesh
              name="Face008"
              castShadow
              receiveShadow
              geometry={nodes.Face008.geometry}
              material={materials["mat_6.002"]}
              userData={{ name: "Face.008" }}
            />
            <mesh
              name="Face009"
              castShadow
              receiveShadow
              geometry={nodes.Face009.geometry}
              material={materials["mat_4.002"]}
              userData={{ name: "Face.009" }}
            />
            <mesh
              name="Face010"
              castShadow
              receiveShadow
              geometry={nodes.Face010.geometry}
              material={materials["mat_6.002"]}
              userData={{ name: "Face.010" }}
            />
            <mesh
              name="Face011"
              castShadow
              receiveShadow
              geometry={nodes.Face011.geometry}
              material={materials["mat_7.002"]}
              userData={{ name: "Face.011" }}
            />
            <mesh
              name="Face012"
              castShadow
              receiveShadow
              geometry={nodes.Face012.geometry}
              material={materials["mat_7.002"]}
              userData={{ name: "Face.012" }}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/kittenbot/ec30_2x2_lr_mh_0.1_magnet_sensor.glb");
