/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/kittenbot/rp2040.glb");
  return (
    <group {...props} dispose={null} position={[0, 1.8, 0]}>
      <group
        position={[13.17, 0.677, 0.0109]}
        rotation={[1.5711, 0.0037, -1.574]}
        scale={1000}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TYPE-C-31-M-12"].geometry}
          material={materials.mat_22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TYPE-C-31-M-12_1"].geometry}
          material={materials.mat_23}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TYPE-C-31-M-12_2"].geometry}
          material={materials.mat_19}
        />
        <group
          position={[-0.0046, -0.0059, 0.0007]}
          rotation={[1.5745, 0.0032, -3.1413]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-Nexperia_SOT23"].geometry}
            material={materials.mat_5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-Nexperia_SOT23_1"].geometry}
            material={materials.mat_6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-Nexperia_SOT23_2"].geometry}
            material={materials.mat_7}
          />
        </group>
        <group
          position={[0.003, -0.024, 0.0009]}
          rotation={[-1.5671, -0.0032, -0.0003]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-0603_LED_Green"].geometry}
            material={materials.mat_8}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-0603_LED_Green_1"].geometry}
            material={materials.mat_9}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-0603_LED_Green_2"].geometry}
            material={materials.mat_10}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-0603_LED_Green_3"].geometry}
            material={materials.mat_11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-0603_LED_Green_4"].geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          position={[0.0048, -0.0062, 0.0007]}
          rotation={[1.6768, -1.5676, -3.0393]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["RC0603N-M"].geometry}
            material={materials.mat_13}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["RC0603N-M_1"].geometry}
            material={materials.mat_14}
          />
        </group>
        <group
          position={[0.0098, -0.0234, 0.0006]}
          rotation={[-1.5672, -0.3523, -0.0004]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RC0603N.geometry}
            material={materials.mat_13}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RC0603N_1.geometry}
            material={materials.mat_14}
          />
        </group>
        <group
          position={[-0.0057, -0.0124, -0.0002]}
          rotation={[1.5745, 0.0032, -3.1413]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-ON_SEMI_SOD123FL"].geometry}
            material={materials.mat_18}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-ON_SEMI_SOD123FL_1"].geometry}
            material={materials.mat_19}
          />
        </group>
        <group
          position={[-0.0087, -0.0029, -0.0001]}
          rotation={[-1.4648, 1.5676, -0.1023]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-ON_SEMI_SOD123FL001"].geometry}
            material={materials.mat_18}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-ON_SEMI_SOD123FL001_1"].geometry}
            material={materials.mat_19}
          />
        </group>
        <group
          position={[-0.0083, -0.006, -0.0002]}
          rotation={[1.5745, 0.0032, -3.1413]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-SOT23-5"].geometry}
            material={materials.mat_12}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-SOT23-5_1"].geometry}
            material={materials.mat_6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-SOT23-5_2"].geometry}
            material={materials.mat_7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-SOT23-5_3"].geometry}
            material={materials.mat_19}
          />
        </group>
        <group
          position={[0.0082, -0.0066, 0]}
          rotation={[-1.5671, -0.0032, -0.0003]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-8-Pin_SOIC_208-mil"].geometry}
            material={materials.mat_24}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-8-Pin_SOIC_208-mil_1"].geometry}
            material={materials.mat_25}
          />
        </group>
        <group
          position={[0.0039, -0.0195, 0.0006]}
          rotation={[0.0037, -0.0003, 0.0032]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-SMD_xtal_32x25mm"].geometry}
            material={materials.mat_26}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-SMD_xtal_32x25mm_1"].geometry}
            material={materials.mat_27}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-SMD_xtal_32x25mm_2"].geometry}
            material={materials.mat_28}
          />
        </group>
        <group
          position={[-0.0023, -0.0246, 0.0008]}
          rotation={[1.5745, 0.0032, -3.1413]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-RCLAMP0521P-N_v2"].geometry}
            material={materials.mat_25}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-RCLAMP0521P-N_v2_1"].geometry}
            material={materials.mat_19}
          />
        </group>
        <group
          position={[0.0049, -0.0245, 0.0008]}
          rotation={[-1.5671, -0.0032, -0.0003]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-RCLAMP0521P-N_v2001"].geometry}
            material={materials.mat_25}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-RCLAMP0521P-N_v2001_1"].geometry}
            material={materials.mat_19}
          />
        </group>
        <group
          position={[0.0001, -0.024, 0.0009]}
          rotation={[-1.4648, 1.5676, -0.1023]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-TZ-P4-1615RGBTCA1-055T-clear-lens"].geometry}
            material={materials.mat_31}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["MSRC-TZ-P4-1615RGBTCA1-055T-clear-lens_1"].geometry
            }
            material={materials.mat_11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["MSRC-TZ-P4-1615RGBTCA1-055T-clear-lens_2"].geometry
            }
            material={materials.mat_32}
          />
        </group>
        <group
          position={[0.0011, -0.0043, 0.0009]}
          rotation={[-1.5671, -0.0032, -0.0003]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-RCLAMP0521P-N_v2002"].geometry}
            material={materials.mat_25}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-RCLAMP0521P-N_v2002_1"].geometry}
            material={materials.mat_19}
          />
        </group>
        <group
          position={[-0.0005, -0.0044, 0.0009]}
          rotation={[1.5745, 0.0032, -3.1413]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-RCLAMP0521P-N_v2003"].geometry}
            material={materials.mat_25}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-RCLAMP0521P-N_v2003_1"].geometry}
            material={materials.mat_19}
          />
        </group>
        <group
          position={[0.0028, -0.0043, 0.0009]}
          rotation={[1.5745, 0.0032, -3.1413]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-RCLAMP0521P-N_v2004"].geometry}
            material={materials.mat_25}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-RCLAMP0521P-N_v2004_1"].geometry}
            material={materials.mat_19}
          />
        </group>
        <group
          position={[-0.0074, -0.0165, -0.0002]}
          rotation={[1.6767, -1.5675, -3.0393]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-ON_SEMI_SOD123FL002"].geometry}
            material={materials.mat_18}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-ON_SEMI_SOD123FL002_1"].geometry}
            material={materials.mat_19}
          />
        </group>
        <group
          position={[0.0089, -0.0164, -0.0001]}
          rotation={[1.6768, -1.5676, -3.0393]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["SOT-23_ONS"].geometry}
            material={materials.mat_33}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["SOT-23_ONS_1"].geometry}
            material={materials.mat_13}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["SOT-23_ONS_2"].geometry}
            material={materials.mat_14}
          />
        </group>
        <group
          position={[-0.0059, -0.0225, -0.001]}
          rotation={[0.0037, -0.0003, -1.5676]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-UK-B0267-SP25Y"].geometry}
            material={materials.mat_10}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-UK-B0267-SP25Y_1"].geometry}
            material={materials.mat_12}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-UK-B0267-SP25Y_2"].geometry}
            material={materials.mat_19}
          />
        </group>
        <group
          position={[0.0085, -0.0206, -0.0001]}
          rotation={[-1.5671, -0.0032, -0.0003]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-Nexperia_SOT23001"].geometry}
            material={materials.mat_5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-Nexperia_SOT23001_1"].geometry}
            material={materials.mat_6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-Nexperia_SOT23001_2"].geometry}
            material={materials.mat_7}
          />
        </group>
        <group
          position={[0.0004, -0.0131, 0.0001]}
          rotation={[1.5745, 0.0032, -3.1413]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-RP2040"].geometry}
            material={materials.mat_5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-RP2040_1"].geometry}
            material={materials.mat_6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["MSRC-RP2040_2"].geometry}
            material={materials.mat_7}
          />
        </group>
        <group
          position={[0.0001, -0.0131, 0.001]}
          rotation={[1.6768, -1.5676, -3.0393]}
          scale={0.0025}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Compound002.geometry}
            material={materials["mat_0.002"]}
            position={[-0.7074, 0, 0.126]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Face.geometry}
            material={materials["mat_1.002"]}
            position={[-0.3749, 0.3149, 0.0584]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Face001.geometry}
            material={materials["mat_2.002"]}
            position={[-0.9592, 0.3199, -0.2491]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Face002.geometry}
            material={materials["mat_3.002"]}
            position={[-0.4996, 0.3199, 0.0831]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Face003.geometry}
            material={materials["mat_1.002"]}
            position={[-1.0202, -0.3149, 0.3392]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Face004.geometry}
            material={materials["mat_2.002"]}
            position={[-2.9903, -0.3199, -0.642]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Face005.geometry}
            material={materials["mat_3.002"]}
            position={[-0.8007, -0.3199, 0.143]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Face006.geometry}
            material={materials["mat_4.002"]}
            position={[-1.5859, 0.3445, -0.3149]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Face007.geometry}
            material={materials["mat_4.002"]}
            position={[-0.7074, -0.3445, 1.0928]}
          />
        </group>
      </group>
      <group scale={2.54}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Compound003.geometry}
          material={materials["mat_0.005"]}
          position={[0.0633, -1.4756, 0.0309]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Face008.geometry}
          material={materials["mat_1.005"]}
          position={[-0.7423, -1.1607, -0.2522]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Face009.geometry}
          material={materials["mat_2.005"]}
          position={[0.4882, -1.1557, 0.4038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Face010.geometry}
          material={materials["mat_1.005"]}
          position={[0.0634, -1.7906, 0.0308]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Face011.geometry}
          material={materials["mat_2.005"]}
          position={[-0.0596, -1.7955, 0.0308]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Face012.geometry}
          material={materials["mat_3.005"]}
          position={[-1.1621, -1.1311, -0.2723]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Face013.geometry}
          material={materials["mat_3.005"]}
          position={[-0.5368, -1.8201, -0.1793]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/kittenbot/rp2040.glb");
