import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import React from "react";
import { Button } from "@mui/material";
import PFHeaderBar from "../components/toolbar/PFHeaderBar";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>MakeDevice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <PFHeaderBar page={"model upload"}></PFHeaderBar>
      </Head>

      <main className={styles.main}>
        <h1>MakeDevice</h1>
      </main>
    </div>
  );
};

export default Home;
