import type { NextPage } from "next";
import styles from "../styles/Home.module.css";
import Head from "next/head";

import React from "react";
import ModelDropzone from "../components/uploader/ModelDropzone";
import PFHeaderBar from "../components/toolbar/PFHeaderBar";
import GLTFDropzone from "../components/uploader/GLTFDropzone";

const ModelUploader: NextPage = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>EasyFab</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
          <PFHeaderBar page={"model uploader"} />
        </header>

        <GLTFDropzone />

        <footer></footer>
      </div>
    </>
  );
};

export default ModelUploader;
