/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/mounting_holes/jacdac_ground_mh_0.1.glb",
  );
  return (
    <group
      {...props}
      dispose={null}
      rotation={[Math.PI / 2, 0, Math.PI]}
      position={[0, -1.9, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHAPE_1_IndexedFaceSet.geometry}
        material={materials.SHAPE_1}
        position={[-0.555, 0.554, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={2.54}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHAPE_2_IndexedFaceSet.geometry}
        material={materials.SHAPE_1}
        position={[-0.555, 0.554, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={2.54}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHAPE_3_IndexedFaceSet.geometry}
        material={materials.SHAPE_3}
        position={[0.394, -0.395, -0.8]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={2.54}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHAPE_4_IndexedFaceSet.geometry}
        material={materials.SHAPE_4}
        position={[-0.555, 0.554, -0.813]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={2.54}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHAPE_5_IndexedFaceSet.geometry}
        material={materials.SHAPE_3}
        position={[-0.555, 0.554, 0.8]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={2.54}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHAPE_6_IndexedFaceSet.geometry}
        material={materials.SHAPE_6}
        position={[-0.555, 0.554, 0.812]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={2.54}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHAPE_7_IndexedFaceSet.geometry}
        material={materials.SHAPE_7}
        position={[1.19, -1.186, -0.875]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={2.54}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHAPE_8_IndexedFaceSet.geometry}
        material={materials.SHAPE_8}
        position={[1.191, -1.189, 0.875]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={2.54}
      />
    </group>
  );
}

useGLTF.preload("/models/mounting_holes/jacdac_ground_mh_0.1.glb");
