/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
TRANSFORMED!!!
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/virtual_modules/vm_jacdaptor_0.2.glb')
  return (
    <group {...props} dispose={null} rotation={[Math.PI / 2, 0, Math.PI]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHAPE_1_IndexedFaceSet.geometry}
        material={materials.PaletteMaterial001}
        position={[-21.132, 0.885, 0.879]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={2.54}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHAPE_4657_IndexedFaceSet.geometry}
        material={materials.PaletteMaterial002}
        position={[-3.632, 4.56, 0.867]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={2.54}
      />
    </group>
  )
}

useGLTF.preload('/models/virtual_modules/vm_jacdaptor_0.2.glb')
