/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "models/virtual_modules/vm_keycap_button_row_0.3.glb",
  );
  return (
    <group
      {...props}
      dispose={null}
      position={[0, 1.1, 0]}
      rotation={[Math.PI / 2, 0, Math.PI]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHAPE_1_IndexedFaceSet.geometry}
        material={materials.PaletteMaterial001}
        position={[-77.755, 5.375, -4.149]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={2.54}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHAPE_4002_IndexedFaceSet.geometry}
        material={materials.PaletteMaterial002}
        position={[-50.155, 0.175, 1.339]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={2.54}
      />
    </group>
  );
}

useGLTF.preload("models/virtual_modules/vm_keycap_button_row_0.3.glb");
