/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
TRANSFORMED!!!
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/virtual_modules/vm_rp2040_pogo_mh_0.1.glb')
  return (
    <group {...props} dispose={null} rotation={[Math.PI / 2, 0, Math.PI]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHAPE_1_IndexedFaceSet.geometry}
        material={materials.PaletteMaterial001}
        position={[-9.359, 11.777, 1.003]}
        rotation={[0, 0, Math.PI]}
        scale={2.54}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHAPE_182_IndexedFaceSet.geometry}
        material={materials.PaletteMaterial002}
        position={[-0.749, 0.171, 0.991]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={2.54}
      />
    </group>
  )
}

useGLTF.preload('/models/virtual_modules/vm_rp2040_pogo_mh_0.1.glb')