/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
TRANSFORMED!!!
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/virtual_modules/vm_rp2040_brain_0.2.glb')
  return (
    <group {...props} dispose={null} rotation={[Math.PI / 2, 0, Math.PI]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shape_IndexedFaceSet.geometry}
        material={materials.PaletteMaterial001}
        position={[7.785, 4.022, 0.007]}
        rotation={[0, 0, Math.PI / 2]}
      />
    </group>
  )
}

useGLTF.preload('/models/virtual_modules/vm_rp2040_brain_0.2.glb')
